[package]
name = "v8-coverage"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
license = "MIT"
edition = "2018"

[dependencies]
rayon = "^1.2.1"
serde = { version = "^1.0.104", features = ["derive"] }
typed-arena = "^1.7.0"

[dev-dependencies]
test-generator = "^0.3.0"
