[package]
name = "v8-coverage"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]

[dependencies]
rayon = "^1.2.1"
serde = "^1.0.103"
serde_derive = "^1.0.103"
typed-arena = "^1.7.0"
