// DO NOT EDIT: generated by `generate-fixtures.js`
const lib = require.resolve('./lib.js')
function main () {
  require("./main.0.js")
  delete require.cache[lib]
  require("./main.1.js")
  delete require.cache[lib]
}
main()
