name: Check the Rust implementation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Use `["1.56.0", "stable"]` once Rust 1.56 is released.
        rust-version: ["beta"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy

      - name: Build and test
        uses: actions-rs/cargo@v1
        with:
          command: test
