name: Check the Rust implementation

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.13.1", "16"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Build and test
        run: |
          cd ts
          yarn install
          yarn run test
          cp coverage/lcov.info coverage.lcov
          yarn run codecov
