name: Check the TypeScript implementation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Use `["14.13.1, "current"]` once 12.x is EOL and the `current` alias is supported.
        node-version: ["12.20.0", "14.13.1", "16"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Build and test
        run: |
          yarn install
          yarn run test
